### ISSUE TITLE
Figure out Moodle version compatibility

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-moodle-plugin#1]
The ```version.php``` mentions Moodle 2.5.3 (11 November 2013) as the minimum requirement.

So far I haven't gotten the plugin to work neither on 2.8 nor 2.7, so apparently something has changed in a non-BC way between Moodle 2.5 and 2.7.

- [ ] Figure out what
- [ ] Figure out how much work it requires to make it work on newer versions

**Comment by juho-jaakkola** [comment]
Or could it be that the included H5P-libraries are just not compatible with the current h5p-packages? I'd guess they've changed since 2013? Not sure.

In any case I'm getting this error when attempting to upload a H5P-file:

> The uploaded file is not a valid H5P.

**Comment by falcon-git** [comment]
Yes, the H5P PHP library included in this Moodle plugin from 2013 is very much outdated, and when that is updatad from https://github.com/h5p/h5p-php-library/tree/stable we need to rewrite the integration between Moodle and that library since much has changed since 2013. I'm afraid we don't have a log pointing out what needs to be changed, but the Wordpress plugin may probably be used as an example https://github.com/h5p/h5p-wordpress-plugin

**Comment by anieminen** [comment]
I did some testing with the plugin in Moodle 2.6 with debugging on. After uploading a H5P file and saving the form I got the same error as @juho-jaakkola mentioned before, and also this debug message:
> Warning: copy(/var/www/moodle/mod/hvp/files/tmp/hvp-564d887f3e834.h5p): failed to open stream: No such file or directory in /var/www/moodle/lib/filestorage/stored_file.php on line 488

It seems that the plugin is trying to read the file from mod/hvp folder under Moodle wwwroot, instead of dataroot where all the uploaded files are usually saved. I created the folder and added write permissions to Apache, and after that I'm getting the same error with different debug message:
> File "README.md" not allowed. Only files with the following extensions are allowed: ...
> line 37 of /mod/hvp/hvp.php: call to debugging()
> line 1420 of /mod/hvp/library/h5p.classes.php: call to H5PMoodle->setErrorMessage()
> line 540 of /mod/hvp/library/h5p.classes.php: call to H5PContentValidator->validateContentFiles()
> line 433 of /mod/hvp/library/h5p.classes.php: call to H5PValidator->getLibraryData()
> line 67 of /mod/hvp/mod_form.php: call to H5PValidator->isValidPackage()

**Comment by icc** [comment]
Yes, you are correct. The files directory under the plugin needs write permission. This was used instead of dataroot which, at the time at least, required integration against the file API of Moodle. Not being able to use the native file operations in PHP requires changes to the h5p-php-library, so just using a separate directory was easier/faster.

To avoid the error message you're getting you must either add .md to the allowed file extension whitelist available in h5p.classes.php or remove the file from the package.

Support for .md files have been added in a later version of h5p-php-library.

**Comment by mgancarzdsi** [comment]
In terms of moodle version targeting, I would recommend targeting 2.7 and up. The reason for 2.7 is that it's on Long-term release support until May 2017. 

I understand that for this prototype the plugin folder writing was a quick workaround, but I would say absolutely one of the requirements for the non-prototype version is that the plugin only write to the moodle dataroot folder. I'm not sure you can even get approval to be listed in the Moodle plugins if you write locally.

**Comment by juho-jaakkola** [comment]
It seems most of the current issues are caused by incompatibility with the latest version of the [h5p-php-library](https://github.com/h5p/h5p-php-library), not the Moodle version. Therefore I'll close this issue for now, and open new, more specific ones if necessary.

I will target the plugin for Moodle 2.7.
