### ISSUE TITLE
i18n Issue (German Language)

### ISSUE THREAD

**Issue by EldoranDev** [h5p/h5p-moodle-plugin#140]
Hello,

when using the H5P Media Type the player shows a strange string on the bottom side next to the download Button.

![screenshot](https://cloud.githubusercontent.com/assets/1896029/24237125/4c8256e2-0fa5-11e7-8a88-51a789ff670b.png)

We are using the Current 1.0 Version (Using the Stable Branch from GitHub) with Moodle 3.2.2
A short grep ```grep -nr '*kennenzulernen*' .``` in the <moodle>/mod/hvp folder did not show any results so we do not know where this extra characters at the end come from.

**Comment by EldoranDev** [comment]
We found the issue ourselfes.

The <moodledata>/lang/de/hvp.php still contained the string and using moodles clear cache did not fix it so we removed the file and now everything is shown as wanted.

**Comment by EldoranDev** [comment]
After removing the cache the issue now occurred again.

**Comment by thomasmars** [comment]
Hi, this is because the "de" language submitted to lang.moodle.org, where H5P gets its language packs have included a html anchor tag where it is not allowed. I have submitted a change proposal to fix this, but the language maintainer of the whole "de" pack has to verify this for it to be changed in the package. When this is accepted you must update the language package and this should be fixed.
Thanks for reporting this.

**Comment by thomasmars** [comment]
It should be fixed now if you update your translation package with the official one from Moodle
