### ISSUE TITLE
Interactive video isn't dispalyed when in guest role

### ISSUE THREAD

**Issue by leac** [h5p/h5p-moodle-plugin#145]
We're running Moodle 3.1.
In one of our courses, when a user logs in as a **guest**, the interactive video doesn't display, and there are errors in the console:

> Unable to find constructor for: H5P.InteractiveVideo 1.12    h5p.js:873:9
> TypeError: instance is undefined     h5p.js:1730:1

But there are 2 cases in which it **is** displayed to the guest:
1. If I add this line to config.php (as advised in [this](https://github.com/h5p/h5p-moodle-plugin/issues/132) issue):
    `$CFG->mod_hvp_dev = 1;`
     Then the vidoe is displayed to guest.

2. If the following steps are taken, then, also the video is displayed to the guest:
   1. I log in as a regular user, 
   2. Then log out 
   3. Then log in as a guest.

If you want to experience it, this issue happens on this [page](http://apps.moodle.ort.org.il/aviv/mod/hvp/view.php?id=1393).  Since the login page is in Hebrew, this screenshot shows which is the Login As Guest button
![image](https://cloud.githubusercontent.com/assets/1826720/24453995/a9fb89be-1492-11e7-8226-1c7c14a565f7.png)

**Comment by thomasmars** [comment]
It seems like the server can't fetch your cached assets for some reason. Can you try setting `$CFG->mod_hvp_aggregate_assets = 0;` in your config.php file ? This should turn of the caching for now, it would be useful for determining if this is the problem.

Does the video display when you log in as a regular user ? Or are you still experiencing the same problem then ?

**Comment by leac** [comment]
Thanks.

I tried setting that, but it doesn't solve the problem.

Regarding users: when I log in as Admin, I can always see the video. However, other users who log in - some of them do see the video and some don't. 

Additionally, we have a similar problem with a  SingleChoiceSet type question. Should I elaborate on it here, or should we focus on the video?

**Comment by thomasmars** [comment]
Okay, I get the following errors on your site when trying to view the content as a guest:
`h5p.js?ver=2016112404:386GET http://apps.moodle.ort.org.il/aviv/pluginfile.php/1/mod_hvp/cachedassets/a4cfaf679366c7bf870a64a963a332c5ab824f04.css 
(anonymous) @ h5p.js?ver=2016112404:386
each @ jquery.js?ver=2016112404:2
each @ jquery.js?ver=2016112404:2
H5P.init @ h5p.js?ver=2016112404:383
(anonymous) @ h5p.js?ver=2016112404:2000
c @ jquery.js?ver=2016112404:2
fireWith @ jquery.js?ver=2016112404:2
ready @ jquery.js?ver=2016112404:2
H @ jquery.js?ver=2016112404:2
2017-04-03 08:49:16.628 h5p.js?ver=2016112404:386GET http://apps.moodle.ort.org.il/aviv/pluginfile.php/1/mod_hvp/cachedassets/a4cfaf679366c7bf870a64a963a332c5ab824f04.js 
(anonymous) @ h5p.js?ver=2016112404:386
each @ jquery.js?ver=2016112404:2
each @ jquery.js?ver=2016112404:2
H5P.init @ h5p.js?ver=2016112404:383
(anonymous) @ h5p.js?ver=2016112404:2000
c @ jquery.js?ver=2016112404:2
fireWith @ jquery.js?ver=2016112404:2
ready @ jquery.js?ver=2016112404:2
H @ jquery.js?ver=2016112404:2
2017-04-03 08:49:16.946 view.php?id=1393:1 GET http://apps.moodle.ort.org.il/aviv/pluginfile.php/1/mod_hvp/cachedassets/a4cfaf679366c7bf870a64a963a332c5ab824f04.js 404 (Not Found)`. What errors are you seeing when setting `$CFG->mod_hvp_aggregate_assets = 0;`. It should be something different since it shouldn't try to fetch the cached assets.
Yes, please elaborate on the SCS errors here as well, they might be connected to the setup of your site.

**Comment by leac** [comment]
I get many more 404's with that parameter turned off. I'm leaving it turned off so you can see for yourself.
Here are just a few:  
```
joubel-help-dialog.css Failed to load resource: the server responded with a status of 404 (Not Found)  
joubel-message-dialog.css  Failed to load resource: the server responded with a status of 404 (Not Found)
joubel-progress-circle.css  Failed to load resource: the server responded with a status of 404 (Not Found)
....
```

In addition I asked @nadavkav, who is a colleague, to test this on another system witch resides in a totally different server, and he confirmed that this bug happens there too.  
We will try to debug the issue ourselves, and would very much appreciate if you could give us any clues as to what could be causing this issue.

**Comment by thomasmars** [comment]
It is hard to say what is going wrong here, the server is not able to serve the libraries, can you check your "H5P Libraries" page and paste the content of that here, to make sure you have the correct libraries installed.

Please also check your server error log and database to make sure that the libraries are actually available on your server. Otherwise there should be some indication in the server error log as to what is going wrong, please paste any relevant information here so we can help you further.

**Comment by nadavkav** [comment]
Upgrading to HVP v1.1 did not solve this issue. so I started an xdebug session as Moodle guest user, but weird enough... while in debug mode, everything works fine. so I turned off debug mode, and not it still works fine. and I can not reproduce this issue anymore (btw, using Moodle 3.1 hvp 1.1 and php7)

**Comment by icc** [comment]
Ensure that the user has the `mod/hvp:getcachedassets` permission/capability.

**Comment by nadavkav** [comment]
Yep, I have set a breakpoint on that one too, as I am also guessing this is the issue. I will keep you updated.

**Comment by nadavkav** [comment]
And ... Thanks! @icc

**Comment by nadavkav** [comment]
Ok. it seems that while upgrading from what ever version we previously had to that current one, that mod/hvp:getcachedassets was not set for guest user. manually setting it fixed the issue. (unsetting it cause the issue to appear again)
This is all on my development server. so, I let @leac try this on the production server. confirm it. and hopefully close it.

**Comment by leac** [comment]
I confirm - I tried it on our production server and it works!

Thank you very much, @icc  and @nadavkav!
