### ISSUE TITLE
A non well formed numeric value encountered in /mod/hvp/library/h5p.classes.php

### ISSUE THREAD

**Issue by davidpesce** [h5p/h5p-moodle-plugin#151]
Got two of the following errors at the upgradesettings.php? portion of installing the plugin:
```
Notice: A non well formed numeric value encountered in mod/hvp/library/h5p.classes.php on line 2982
```

**Comment by thomasmars** [comment]
Thank you for reporting this, could you tell me what your `upload_max_filesize` and `post_max_size` is set to in your php.ini config ? and alternatively what argument is passed to the `returnBytes($val)` function at line 2982 of h5p.classes.php ?
The error is most likely caused by us assuming that you have a numeric value for these options, but something different is passed in. Please also let us know what version of PHP you are running. 
Thanks!

**Comment by davidpesce** [comment]
post_max_size = 20M
upload_max_filesize = 20M

**Comment by davidpesce** [comment]
PHP v7.1.1

**Comment by thomasmars** [comment]
Thanks, the notice is a new addition in PHP 7.1 and is shown because we do arithmetic on a string before casting it to an int. The message is only a notice and should not cause any problems for your site. You can read more about it at [php's 7.1 migration page](http://php.net/manual/en/migration71.other-changes.php#migration71.other-changes.apprise-on-arithmetic-with-invalid-strings)
I have created an [issue](https://h5ptechnology.atlassian.net/browse/HFP-1085) for it in the public tracker, which will hopefully be resolved soon. Thanks for reporting this.
