### ISSUE TITLE
Improvement: have a 'finish my attempt' button

### ISSUE THREAD

**Issue by elearningdave** [h5p/h5p-moodle-plugin#167]
We love the idea of using some of these tools, we've only shown a couple to staff and they were genuinely interested in using them for flipped learning.
However, it doesn't score partially completed scores that we can find - teachers need to know if a student only got 2 out of 6, and which 2 ideally.
Also, it would help if your Activity Completion heading on an instance's settings allowed you to save the pass mark. So it's more in unison with the moodle setting used for quizzes etc.

**Comment by thomasmars** [comment]
Hi,
I'm happy to hear of the interest :)
Score is only saved when a content type has been completely answered. For compound tasks this means that the user must complete all subtasks, or move to a summary/finished page or similar to get their score registered. This is up to the individual content type implementation, so this will necessarily have to be fixed in the individual content type's repository if the functionality is insufficient for that content type.
Pass mark can be set up in the gradebook setup for each activity.
This should already be in place, let me know if I misunderstood something.

**Comment by elearningdave** [comment]
I haven't checked on the gradebook thing. I'll log the improvement with the first content type, but really ANY content type where there is more than one correct answer, and the user may not complete all the subtasks, should have the same improvement done.
