### ISSUE TITLE
Standard capability not defined

### ISSUE THREAD

**Issue by 2shediac** [h5p/h5p-moodle-plugin#171]
Get the following message when trying to add Module to a course version 2017083100:
The module hvp does not define the standard capability mod/hvp
line 2422 of /course/lib.php: call to debugging()
line 436 of /course/modlib.php: call to course_allowed_module()
line 63 of /course/modedit.php: call to can_add_moduleinfo()

Also when activity is added to the course - see the following on the editor:
The H5P library {$a->%library} used in the content is not valid;

**Comment by thomasmars** [comment]
Hi,
I'm not able to reproduce this.
Can you give a detailed run-through of how I can reproduce this ?
When does it happen, do you have anything special in your setup ?

This error will typically happen when you try to save newly created content without having selected
any H5P library, but could perhaps be caused by something else. We need more information from you to resolve it.

**Comment by 2shediac** [comment]
I re-installed a clean version of Moodle to validate and also reset my internet connection. It looks like those items cleared the problem up. 

I will test some more but for now consider the problem resolved.
