### ISSUE TITLE
Functionality to remove libraries

### ISSUE THREAD

**Issue by zaydons** [h5p/h5p-moodle-plugin#175]
It would be pretty great to have the functionality to delete libraries..

**Comment by timothyylim** [comment]
Thanks for catching this @zaydons, I've made an issue for it here:

https://h5ptechnology.atlassian.net/browse/HFP-1635

**Comment by falcon-git** [comment]
I believe it was left out intentionally since libraries can't really be deleted anyway because of circular dependencies. We will re-implement the entire library management with a deletion feature that can handle circular dependencies and other features like being able to only show the latest version of each library.
