### ISSUE TITLE
Mod_hvp 1.6 upgrade "embed button" default setting doesn't work consistently

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#187]
Hello,

It seems when you update mod_hvp to version 1.6 Moodle lets you select from the new available default settings for it f.ex "Embed button" and default settings is "always on", if you select "controllered by author, default is off" still some old H5P-activities have embed button on by default and some don't. 

It's like the installation doesn't disable it by default if you choose it.

![h5pupotus](https://user-images.githubusercontent.com/15193418/34295996-f8fda17e-e718-11e7-8a51-696c70a5ddba.PNG)

**Comment by Jarvil** [comment]
@thomasmars any ideas?

**Comment by thomasmars** [comment]
Old content will not be affected when you change the default option in "Embed button"; only new content. Old content will keep its current settings because we can not determine if it was explicitly set by author or was untouched.

**Comment by Urpokarhu1** [comment]
Hello,

This is a new feature in hvp 1.6 so it doesn't make sense that old activities doesn't follow the setting you choose (they don't have this option until this update)

**Comment by thomasmars** [comment]
Exactly, that's what I'm saying. For old content the embed option will stay the same as it was for that content.
For old content we have no way to know whether the embed button visibility option was set explicitly by the author or not. That is why we assume that for all old content the embed button visibility option was set by the author.
If we on the other hand assumed that for all old content the embed button visibility option should follow the new default, an author that had configured all of his content with specific settings for the embed button would lose all their previous settings, which is something we absolutely don't want.

**Comment by Urpokarhu1** [comment]
Hello,

You don't understand, old activites didn't have this option so it can't be the same since it wasn't there at all :)

**Comment by thomasmars** [comment]
Okay, sorry, I think I understand what you mean now. 
Content that was created before the embed display options was introduced will have embed options on. This is because of how the display options are implemented in H5P core, by default every display option is enabled, and then you can disable them as you please. Since it wasn't possible to disable the embed option before, all old content was created with the embed option turned on, so the embed visibility option is always set to true for old content.
They will not be affected by the new default visibility option since this option is inherently chosen for them.
