### ISSUE TITLE
Embed includes resizer

### ISSUE THREAD

**Issue by mkpelletier** [h5p/h5p-moodle-plugin#196]
Hi All,

I have been using the embed feature on my courses.  It is great!  Thanks for adding that in.  There is one small problem, however, in that the code includes the resizer script.  Is it not better to simply include the resizer once after the body tag in the site, rather than to include it every time you embed the iframe?  It seems to me that including the script over and over again will adversely affect page load performance, no?

I seem to recall reading somewhere in your documentation that this is the correct thing to do, but I can't remember where I read it.  In any case, I have the resizer included at site level, so there is no need to keep including it with each embedded iframe.  I am happy to be corrected here, but I _think_ that's right.

**Comment by icc** [comment]
You are correct, it only has to be included once on the page.
However, the impact of having it multiple times should be unnoticeable as it's cached in the browser(if the web server is set up correctly).
You can also choose to not have it all, but then the size of the content will be static and probably get scrollbars as the content changes.
I guess it's always included since most content change size and then people start complaining about scrollbars, i.e. there's a bigger benefit to always having it.
