### ISSUE TITLE
Deleting course with h5p activity causes an error "Error reading to the database"

### ISSUE THREAD

**Issue by dvillareal22** [h5p/h5p-moodle-plugin#205]
Hi All,

We used the newest version and it seems that we found a bug.
the column author was missing on the table mdl_hvp.
When I checked the install.xml and upgrade.php to trace that it seems that the author column should be authors.
So I've checked the backup_hvp_stepslib.php line 94 which was being triggered on moodle delete course there are columns there that cause some error.

I found out that the meta_keyword and meta_description was being removed (upgrade.php). 

So I fixed the bug by changing h.author to h.authors and removed h.meta_keywords, h.meta_description,

**Comment by CinecaElearning** [comment]
Hello,
we found the same problem and, thanks to Daniel Villareal, found a fast solution! Thanks again Daniel!

**Comment by fnoks** [comment]
I suspect you are using the master branch of the Moodle plugin. If I am correct, you should know this is the development branch, and it is not intended for a production environment. If you do use it in production, I will promise you will get into major problems.

If you need to use github as the source for the code (instead of using regular Moodle installs via moodle.org), please use the stable branch, which will contain the same code as the latest released version.
