### ISSUE TITLE
framework.php missing some creative commons attributions variations

### ISSUE THREAD

**Issue by js0000** [h5p/h5p-moodle-plugin#209]
hi

the plugin is great- we're just getting our feet wet, but it seems like a great way forward. thx!

i'm running hvp ($plugin->version   = 2018062800) on my moodle instance (version Moodle 3.3.6 (Build: 20180517)) on php 7.1.18 

i kept getting lookup errors regarding missing license variations within framework.php, so i added them. i'm attaching a a patch. one of the additions may be a fixing typo, but i left the original in place because it caused no harm.

please feel free to follow up with me if i can help more- and keep up the good work!

[framework.php.diff.txt](https://github.com/h5p/h5p-moodle-plugin/files/2283250/framework.php.diff.txt)

**Comment by H5P-Helper** [comment]
Hi,

Could you please create a Pull Request here instead:
https://github.com/h5p/h5p-moodle-plugin ?

Kind regards,

Pål Jørgensen

h5p/h5p-moodle-plugin on August 13, 2018 at 4:17pm wrote:

hi

the plugin is great- we're just getting our feet wet, but it
seems like a great way forward. thx!

i'm running hvp ($plugin->version = 2018062800) on my moodle
instance (version Moodle 3.3.6 (Build: 20180517)) on php 7.1.18

i kept getting lookup errors regarding missing license variations
within framework.php, so i added them. i'm attaching a a patch.
one of the additions may be a fixing typo, but i left the
original in place because it caused no harm.

please feel free to follow up with me if i can help more- and
keep up the good work!

framework.php.diff.txt 
( https://github.com/h5p/h5p-moodle-plugin/files/2283250/framework.php.diff.txt )


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/h5p/h5p-moodle-plugin/issues/209 ), or mute
the thread
