### ISSUE TITLE
Remove libraries from the system

### ISSUE THREAD

**Issue by tobiasreischmann** [h5p/h5p-moodle-plugin#214]
We would be interested in removing libraries from the system, when they should no longer be accessible to the teachers. Although a method deleteLibrary exists in the framework, it does not work as expected (due to wrong comments; $libraryid is supposed to contain the whole library entry). Additionally, it only removes the single library, without its dependencies and leaves existing instances in an erroneous state.

**Comment by thomasmars** [comment]
Thanks, I've created an issue for adding the delete button to the library administration page: https://h5ptechnology.atlassian.net/browse/HFP-2168. We don't delete all dependencies of a library when deleting a library since other libraries may have the same dependencies or the dependencies may be runnable libraries themselves. You may write your own logic for a recursive delete of a library though by checking whether the dependencies are in use.
