### ISSUE TITLE
Mod_hvp 1.17.2, unlock completion options" doesn't work at all

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#264]
Hello,

There is a bug in mod_hvp version 1.17.2, you cannot click "unlock completion options" in H5P-activity in Moodle, if you do you will be redirected to the course front page and completion settings are not unlocked. Tested with Moodle 3.5.5

It doesn't matter which H5P library you are using.

So at the moment you cannot change h5p-activity completion settings at all in Moodle.

![image](https://user-images.githubusercontent.com/15193418/55536732-2de36700-56c3-11e9-8478-7d1927c2a1df.png)

 @thomasmars

**Comment by thomasmars** [comment]
Afaik this is controlled by Moodle, we don't have any specific logic for handling this in the H5P plugin.

**Comment by Jarvil** [comment]
Hello,

I tried with earlier version of mod_hvp in the same Moodle and they worked, which is peculiar if H5P itself doesn't handle this.

**Comment by Jarvil** [comment]
Hello,

I tried with another Moodle (3.5.5) with earlier version of mod_hvp and everything worked fine I could unlock the completion options -> upgraded the mod_hvp plugin -> doesn't work anymore but takes me back to the course front page.

**Comment by thomasmars** [comment]
Thanks for the information. I've created an issue for looking into this at https://h5ptechnology.atlassian.net/browse/HFP-2714.
We would be grateful for any additional info on what could be causing this and a pull request if you're able to dig deeper into the issue and solve it.

**Comment by anieminen** [comment]
Hi,

User is also redirected to course front page after submitting the activity settings form with "Save and display" button. This is not a big problem because other settings are saved anyway. But the "Unlock completion options" button is a special case, it should reload the same form and then you can decide if you want to submit and empty the completion data.

I did some quick debugging, and it seems that user is redirected back to course page because `submitbutton` is missing from the posted form data.
https://github.com/moodle/moodle/blob/MOODLE_35_STABLE/course/modedit.php#L159

**Comment by thomasmars** [comment]
Thanks for reporting this and the additional debugging info. It should be fixed by https://github.com/h5p/h5p-editor-php-library/commit/87d5cfd03a1ac58fb7d17ec75fa5a003c22339e7. Please try it out and let me know how it works out for you. Will be part of the next plugin release.

**Comment by anieminen** [comment]
Thank you! I applied the fix and it seems to work as expected.
