### ISSUE TITLE
Upgrade from install after 2018090300 version point misses metadata column name change

### ISSUE THREAD

**Issue by pauldamiani** [h5p/h5p-moodle-plugin#267]
Hi,
We recently tried to upgrade the plugin from version 1.10 to 1.17.2
Doing so caused an issue which caused the plugin to incorrectly display that libraries weren't installed.

We traced it back to a change in the database schema where in the table hvp_libraries, the column metadata was renamed to metadata_settings.
We used git to install the H5P plugin as a submodule and were on commit 892a5. The schema was changed a day later, but because we had already passed the upgrade point version 2018090300, the rename was never applied.

**Comment by thomasmars** [comment]
When using the H5P plugin from the github repository, make sure to use it from a release tag or from the 'stable' branch, as explained in the readme. We can't guarantee that the other branches are stable or will be compatible with upcoming releases.
Since you have been working from a commit that was not on the stable branch you will have to do a manual migrations to make sure that any missed upgrade points are performed.
