### ISSUE TITLE
Can't create new instances within Moodle 3.7.1

### ISSUE THREAD

**Issue by ralfhilg** [h5p/h5p-moodle-plugin#281]
Moodle 3.7.1 H5P  Plugin 2019052100

Its not possible to create new instances. The field for name/title of activity is not visible. 
![h5p](https://user-images.githubusercontent.com/41056305/61612143-f1ca1700-ac5d-11e9-83ff-0f67d7c32464.PNG)

**Comment by otacke** [comment]
Hi @ralfhilg !

I just updated a local plain moodle instance with H5P 1.18 (2019052100) to 3.7.1 (2019052100) in order to verify your problem, but I can't reproduce it. The H5P editor still show up below the _Description_ section as usual for both, existing and new content.

Could you possibly provide some more information?

Cheers,
Ollie

**Comment by ralfhilg** [comment]
I tried it now with Boost and default preset and also with Classic and got the same result.  I will install the plugin on an other site and retry.

**Comment by ralfhilg** [comment]
We could solve the problem here. Sometimes the problem is the user.
