### ISSUE TITLE
IE11 reuse doesn't offer h5p files but zip files

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/h5p-moodle-plugin#304]
Hello,

mod_hvp 1.1 Release 1.19.1 offers through reuse H5P-presentation as zip file and not as .h5p file, is this a bug?

**Comment by thomasmars** [comment]
Hi, I just tested this with Moodle 3.7.1+ (Build: 20190830) with 1.19.1 and it works fine for me.
Sounds like this could be a server issue. Ensure that at least the following is being set for the response headers:
```
Content-Disposition: inline; filename="h5p-name.h5p"
Content-Length: 5797258(depends on your h5p)
Content-Type: application/zip
```

I've also added a fix for the warning in Chrome when downloading, which might help: https://github.com/h5p/h5p-php-library/commit/b07143724c94e9265df4293c824643dfcc1dab75.
Let me know if you're still experiencing this after checking your headers and trying out the patch.

**Comment by Urpokarhu1** [comment]
Hello,

We cannot get this to work, IE11 just offers .zip file instead of .h5p file, any more advice?

We have changed apache settings that it will block IE from examining the file type;

Header set X-Content-Type-Options: "nosniff"

We have added mimetype to /etc/mime.types;
application/zip zip h5p

We have also tried application/x-zip-compressed

**Comment by thomasmars** [comment]
Are the headers i described set for your request when you inspect it ?
Did you try with the patch I suggested ?

**Comment by Urpokarhu1** [comment]
Hello,

I just added the image, we haven't tried the patch yet because I thought you said it was fixin Chrome-problem, not IE11 problem.

**Comment by thomasmars** [comment]
Yeah, you're right, thanks for adding the screenshot. The steps you've taken to try to fix it sounds reasonable, it sounds like IE11 sees that it is essentially a zip file and change the extension because of this.

I googled the problem a bit and found a similar case: [[1](https://answers.microsoft.com/en-us/ie/forum/all/ie11-changes-file-extension/ccdb5899-4f45-478f-94f7-c38ec95c8aa3)]. It sounds like this is a problem with IE11, and perhaps in combination with the OS. You could try resetting the browser settings or reinstalling IE11, but I'm not sure it will yield any results.

Unfortunately, I don't think there's much we can do to fix the issue on our side. Please let us know if you find a solution.

**Comment by icc** [comment]
Setting the `X-Content-Type-Options: nosniff` header should solve this, unless the web server or Moodle is specifically sending the application/zip content type. Please double-check the headers.
More info: https://blogs.msdn.microsoft.com/asiatech/2012/03/28/office-documents-will-be-recognized-as-zip-file-when-downloading-from-ie/
