### ISSUE TITLE
Add Stats for Each Embedded Question

### ISSUE THREAD

**Issue by SanatSharma** [h5p/h5p-moodle-plugin#341]
Hi,
I was wondering what work would be required to add Stats for each question after the student answers the embedded question.
We want to add usage stats such as "80% of students got this right" after the student answers. The data will be picked up from Moodle database. I'm willing to code this feature if some guidance can be given on where the data is stored.

**Comment by thomasmars** [comment]
What do you mean by embedded question ? All H5P activities store their scores through the Moodle Gradebook API. I'm not sure, but I believe Moodle should have some aggregation of grades over an activity:
- https://docs.moodle.org/dev/Gradebook_API 
- https://docs.moodle.org/38/en/Grade_aggregation
I think looking at that is a good starting point. If there's nothing existing already that can generate the stats you need you could use the gradebook api to generate the stats, but you would have to figure out where to put it. An option would be grade.php which shows all grades for a given H5P activity. It could also show the aggregate.

**Comment by SanatSharma** [comment]
Hi Thomas, I meant the average score for all users for that question to appear in the h5p-question-score-container when the user answers the question. I can do the aggregation part with a sql query but am unsure of how to add to that element.
![image](https://user-images.githubusercontent.com/14241701/81872560-909e6780-953f-11ea-88c2-786585b913e2.png)

**Comment by thomasmars** [comment]
The content type is within an iframe, so you would have to hook into the iframe and add some script there if you want to add additional elements within the content type without changing the content type itself. You could use the hvp_alter_scripts() (https://github.com/h5p/h5p-moodle-plugin/blob/stable/classes/editor_framework.php#L239) function for the renderer to add your own script.

You would also need some way to communicate with the backend in order to fetch the aggregated data, and you would have to figure out how to aggregate it and who would have access to it. Or alternatively you could always send it in with the H5PIntegration object and fetch it from there (https://github.com/h5p/h5p-moodle-plugin/blob/stable/locallib.php#L39-L88).

**Comment by SanatSharma** [comment]
Hi Thomas, thanks for the info. I'm still a bit confused. 
The aggregated data will be per embedded question and hence I don't think I can send it through the H5PIntegration Object. 
Is there an example for adding additional scripts that I could follow? Furthermore, i'm unable to find the iframe details in the h5p plugin. I'm able to reach the code where the user score is retrieved when I'm debugging in the browser, but unable to see that in the actual codebase. For example, the function showCheckSolution() as well as getMaxScore() are available in the js files but not in the plugin codebase. Is there something I'm missing.

**Comment by thomasmars** [comment]
H5PIntegration contains data per content id (https://github.com/h5p/h5p-moodle-plugin/blob/stable/classes/view_assets.php#L67)
https://github.com/h5p/h5pmods-moodle-plugin shows an example of adding JS to the Interactive Video content type.
The plugin code and the code for each of the content type are separate repositories, the repositories can be found at https://github.com/h5p
