### ISSUE TITLE
Error loading CSS and JS on Moodle

### ISSUE THREAD

**Issue by aerosmesh** [h5p/h5p-moodle-plugin#63]
Hi,

I install H5P plugin on a moodle 3.0 version, without problems, but when i create a new activity on a course, simply i can´t see anything...

Then i start inspect element on google chrome and see just the attached image

![1](https://cloud.githubusercontent.com/assets/19270262/15120272/2b3509ee-15d2-11e6-85f6-71bf3b5bc5f5.png)

I install the same plugin on a same moodle version running in desktop mode to test and there everything works fine.

Any suggestion is welcome.

Thanks in advance!

**Comment by icc** [comment]
I haven't seen this issue before. Could you try to check your web server's error log for any messages that might be related to this? If possible you could try to enable some debugging options in config.php to gather some more info:
```
@error_reporting(E_ALL | E_STRICT);
@ini_set('display_errors', '1');
$CFG->debug = (E_ALL | E_STRICT);
$CFG->debugdisplay = 1;
```
Remember to remove them afterwards as they are not intendet for production environments.

To help pinpoint when the error happens, you could check if the file that fails to load exist in your database:
```
select timecreated from mdl_files where filename='7649251df2c555...js';
``` 
This will tell us if the error happens when the file is created, or when it's loaded. I'm guessing it's the first one.

You are most likely to see the PHP error messages after updating or uploaded the content.

Hopefully we can solve this before we release the complete version of the plugin.

**Comment by AurelienDM** [comment]
Hi,
I have the same problem as mentioned above.

- moodle version : 3.3
- h5p version : 1.6

<img width="1280" alt="screen shot 2017-12-28 at 06 50 35" src="https://user-images.githubusercontent.com/29572435/34401444-a6d43cd2-eb9b-11e7-97d4-0bbb078d4832.png">
<img width="1280" alt="screen shot 2017-12-28 at 06 53 36" src="https://user-images.githubusercontent.com/29572435/34401490-e5569888-eb9b-11e7-9699-75d6cc9bafe4.png">

I have tried to play with the cache settings in moodle but so far no success..

Thank you

**Comment by icc** [comment]
@AurelienDM Does it work if you try to open the failing URL / resource in a new tab?

Could you try to double check in another browser or on another computer to ensure this isn't a browser issue?

**Comment by AurelienDM** [comment]
@icc The problem got worse it now doesn't work on any browser. 
It seems like caches aren't accessible anymore. Is cloudflare responsible for this issue ? 
eg : https://moodle.aflahaye.nl/mod/hvp/view.php?id=885

**Comment by icc** [comment]
Yes, this may be some sort of web server issue.
