### ISSUE TITLE
Required moodle version

### ISSUE THREAD

**Issue by andipabst** [h5p/h5p-moodle-plugin#73]
As the plugin requires the module mod_assign, which is just available from moodle 3.1, it breaks older moodle instances on installation, at least for me.
So probably the required value in the version.php should be increased to 2016052300?

**Comment by icc** [comment]
I don't think the plugin should require mod_assign. What makes you believe it does?
The idea is to support the oldest still supported version of Moodle, which is 2.7.

**Comment by LukeCarrier** [comment]
The plugin requires at least Moodle 2.6 (`2013051400`; see [Releases on MoodleDocs](https://docs.moodle.org/dev/Releases#Moodle_2.6)), since it makes use of the [`classloader`](https://docs.moodle.org/dev/Automatic_class_loading) added in that release. It will not function on Moodle 2.5.3 (`2013051403`). Would you accept a PR to bump this?

As far as I can tell, there is no dependency on `mod_assign`.
