### ISSUE TITLE
Add RTL support to the H5P Editor

### ISSUE THREAD

**Issue by nadavkav** [h5p/h5p-moodle-plugin#81]
We (The RTL folks) missing an RTL/LTR button on the editor's toolbar, everywhere text can be edited.
Example:
![image](https://cloud.githubusercontent.com/assets/231168/16170267/f414d63a-3555-11e6-83d2-5db3243c2601.png)

(I am referring to Text flow, and not the Alignment)

**Comment by nadavkav** [comment]
Looking at the underlying CKEditor code, it seem trivial to add the RTL/LTR buttons, even to the "Basic" toolbar layout. as they are very important to us (RTL folks)

Also set `config.contentsLangDirection = 'rtl';` when the calculated current language in Moodle for the current user is RTL. when the editor initiates.

Another improvement could be, is to add an `rtl` class to the h5p iframe and a corresponding RTL stylesheet file. maybe a H5P core library?

**Comment by thomasmars** [comment]
This must be implemented in core, so closing this issue.

**Comment by nadavkav** [comment]
Just in case anyone reads this issue...
Here is a link to h5p-moodle-plugin with RTL support:
https://github.com/iucc/h5p-moodle-plugin/commits/v118_rtl_support

**Comment by thomasmars** [comment]
@nadavkav Thanks, it is a good reference. I see that the library and editor has been swapped out in your branch. That is in line with why I'm closing this issue. 
In order to support RTL in H5P it has to be implemented generally in H5P Core and H5P editor, so that it is supported across all H5P integrations. The changes must be made there, not here in the H5P Moodle integration.

**Comment by nadavkav** [comment]
@thomasmars , I guess I miss understood you and thought you meant "Moodle core" and not H5P core. oups.
I completely agree with you now :-)
